# Generated by Django 5.0.1 on 2024-05-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esrog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='esrogim_images/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('size', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
